###
# Spring settings
###
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logDB
    username: logisticsappuser
    password: LogisticsPASS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update