###
# Spring settings
###
spring:
  profiles:
    active: dev
  security:
    jwt:
      access-validity: 900000
      refresh-validity: 86400000
      access-cookie-name: 792F423F4528482B
      refresh-cookie-name: 566B597033733676
      access-cookie-lifetime: 900
      refresh-cookie-lifetime: 86400
      secret: 2F423F4528482B4D6251655468566D597133743677397A24432646294A404E63
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#Spring server settings
server:
  #Servlet Settings
  servlet:
    context-path: /api